name: 'MBX Security'

on: [pull_request]

permissions:
  contents: read
  pull-requests: write # this is to enable PR comments

jobs:
    hello-world:
      name: 'Configured'
      runs-on: ubuntu-latest
      steps:
        - name: echo
          run: echo "Hello World!"
    dependency-review:
      name: 'Dependency Review'
      uses: mapbox/.github-private/.github/workflows/dependency-review.yml@main
