name: 'MBX Security'

on: [pull_request]

permissions:
  actions: read
  checks: read
  contents: read
  deployments: read
  id-token: write
  issues: write
  discussions: read
  packages: read
  pages: read
  pull-requests: write
  repository-projects: read
  security-events: write
  statuses: read

jobs:
  main:
    name: 'Main'
    uses: mapbox/.github-private/.github/workflows/main-testing.yml@main
    secrets: inherit
